name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    label: 'enhancement'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
template: |
  ## Changes

  $CHANGES
autolabeler:
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
  - label: 'bug'
    branch:
      - '/bug\/.+/'
      - '/bugfix\/.+/'
  - label: 'chore'
    branch:
      - '/chore\/.+/'
