name: givt_app_kids
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.5.5

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  amplitude_flutter: ^3.16.1
  countup: ^0.1.4
  currency_text_input_formatter: ^2.1.8
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.0+1
  get_it: ^7.6.4
  go_router: ^13.0.1
  http: ^0.13.5
  http_interceptor: ^1.0.2
  hydrated_bloc: ^9.1.1
  intl: ^0.18.0
  lottie: ^2.1.0
  mobile_scanner: ^2.1.0
  package_info_plus: ^4.0.1
  path_provider: ^2.0.15
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  vibration: ^1.7.6
  visibility_detector: ^0.3.3
  nfc_manager: ^3.3.0
  loading_animation_widget: ^1.2.0+4
  bloc: ^8.1.2
  flutter_guid: ^0.3.1
  flutter_layout_grid: ^2.0.5
  material_color_utilities: ^0.5.0
  font_awesome_flutter: ^10.6.0
  pinput: ^3.0.1
  google_fonts: ^4.0.4
  device_info_plus: ^9.1.1
  ios_utsname_ext: ^2.2.0
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"  

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lotties/
    - assets/icon/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
    - family: RadioCanada
      fonts:
        - asset: assets/fonts/RadioCanada-Regular.ttf
          weight: 400
    - family: Rouna
      fonts:
        - asset: assets/fonts/Rouna-Bold.otf
          weight: 700

dependency_overrides:
  intl: ^0.18.0
