name: givt_app_kids
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.6.17

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  amplitude_flutter: ^3.16.2
  countup: ^0.1.4
  currency_text_input_formatter: ^2.2.3
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  firebase_core: ^2.28.0
  firebase_crashlytics: ^3.4.18
  firebase_remote_config: ^4.4.0
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  go_router: ^14.2.3
  http: ^1.2.2
  http_interceptor: ^2.0.0
  hydrated_bloc: ^9.1.5
  intl: ^0.19.0
  lottie: ^3.1.2
  mobile_scanner: ^5.1.1
  package_info_plus: ^8.0.2
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  vibration: ^2.0.0
  nfc_manager: ^3.5.0
  loading_animation_widget: ^1.2.1
  bloc: ^8.1.4
  material_color_utilities: ^0.11.1
  font_awesome_flutter: ^10.7.0
  pinput: ^5.0.0
  google_fonts: ^6.2.1
  device_info_plus: ^10.1.2
  ios_utsname_ext: ^2.3.0
  logging: ^1.2.0
  path: ^1.9.0
  responsive_sizer: ^3.3.1
  uuid: ^4.4.2
  app_settings: ^5.1.1
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0
  flutter_layout_grid: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lotties/
    - assets/icon/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
    - family: RadioCanada
      fonts:
        - asset: assets/fonts/RadioCanada-Regular.ttf
          weight: 400
    - family: Rouna
      fonts:
        - asset: assets/fonts/Rouna/rouna-bold-webfont.ttf
          weight: 700
        - asset: assets/fonts/Rouna/rouna-medium-webfont.ttf
          weight: 500
        - asset: assets/fonts/Rouna/rouna-regular-webfont.ttf
          weight: 400

dependency_overrides:
  intl: ^0.18.0
