name: Build Android and upload to Play Store
on: 
  workflow_call:
    secrets:
      CODESIGNING_DEPLOY_KEY:
        required: true
      GOOGLE_PLAY_JSON_KEY:
        required: true
      MATCH_PASSWORD:
        required: true
      LOGIT_API_KEY:
        required: true
      GOOGLE_SERVICES_JSON_G4K:
        required: true
    inputs:
      flutter-version:
        required: true
        type: string

jobs:

  build-droid: 
    name: Build Flutter Android
    runs-on: ubuntu-22.04
    steps:
      - name: Set environment variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "Running on the main branch, deploying to production."
            echo "PACKAGE_NAME=net.givtapp.kids" >> $GITHUB_ENV
            echo "FLAVOR=production" >> $GITHUB_ENV
          else
            echo "Running on a different branch, deploying to test."
            echo "PACKAGE_NAME=net.givtapp.kids.test" >> $GITHUB_ENV
            echo "FLAVOR=development" >> $GITHUB_ENV
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with: 
          bundler-cache: true

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
        
      - name: Auth codesigning
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.CODESIGNING_DEPLOY_KEY }}
        
      - name: Replace google-services.json
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON_G4K }}" | base64 --decode > android/app/google-services.json

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: ${{ inputs.flutter-version }}

      - name: Run Fastlane - Development version
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: maierj/fastlane-action@v2.3.0
        with:
          lane: android development
          subdirectory: android
        env:
          GOOGLE_PLAY_JSON_KEY: ${{ secrets.GOOGLE_PLAY_JSON_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          LOGIT_API_KEY: ${{ secrets.LOGIT_API_KEY }}
          PACKAGE_NAME: ${{ env.PACKAGE_NAME }}
          FLAVOR: ${{ env.FLAVOR }}

      - name: Run Fastlane - Production version
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: maierj/fastlane-action@v2.3.0
        with:
          lane: android production
          subdirectory: android
        env:
          GOOGLE_PLAY_JSON_KEY: ${{ secrets.GOOGLE_PLAY_JSON_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          LOGIT_API_KEY: ${{ secrets.LOGIT_API_KEY }}
          PACKAGE_NAME: ${{ env.PACKAGE_NAME }}
          FLAVOR: ${{ env.FLAVOR }}