name: Build and sign iOS
on: 
  workflow_call:
    secrets:
      MATCH_PASSWORD:
        required: true
      APPSTORECONNECT_PRIVATE_KEY:
        required: true
      GITHUB_API_TOKEN:
        required: true
      LOGIT_API_KEY:
        required: true
      CODESIGNING_DEPLOY_KEY:
        required: true
    inputs:
      flutter-version:
        required: true
        type: string

jobs:
  build-ios: 
    name: Build Flutter iOS
    runs-on: macos-latest
    steps:
      - name: Set environment variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "Running on the main branch, deploying to production."
            echo "PACKAGE_NAME=net.givtapp.kids" >> $GITHUB_ENV
            echo "FLAVOR=production" >> $GITHUB_ENV
            echo "TRACK=production" >> $GITHUB_ENV
          else
            echo "Running on a different branch, deploying to test."
            echo "PACKAGE_NAME=net.givtapp.kids.test" >> $GITHUB_ENV
            echo "FLAVOR=development" >> $GITHUB_ENV
            echo "TRACK=internal" >> $GITHUB_ENV
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with: 
          bundler-cache: true

      - name: Auth codesigning
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.CODESIGNING_DEPLOY_KEY }}

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: ${{ inputs.flutter-version }}

      - name: Run Fastlane Testflight Dev/Custom branch
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: maierj/fastlane-action@v2.3.0
        with:
          lane: ios testflight_release
          subdirectory: ios
        env: 
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APPSTORECONNECT_PRIVATE_KEY: ${{ secrets.APPSTORECONNECT_PRIVATE_KEY }}
          LOGIT_API_KEY: ${{ secrets.LOGIT_API_KEY }}
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}
          PACKAGE_NAME: ${{ env.PACKAGE_NAME }}
          FLAVOR: ${{ env.FLAVOR }}

      - name: Run Fastlane Production
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: maierj/fastlane-action@v2.3.0
        with:
          lane: ios prod_release
          subdirectory: ios
        env: 
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APPSTORECONNECT_PRIVATE_KEY: ${{ secrets.APPSTORECONNECT_PRIVATE_KEY }}
          LOGIT_API_KEY: ${{ secrets.LOGIT_API_KEY }}
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}
          PACKAGE_NAME: ${{ env.PACKAGE_NAME }}
          FLAVOR: ${{ env.FLAVOR }}
