name: Build & Deploy

on:
  push:
    branches:
      - main
      - pre-main
      - new_pipeline

jobs:
    droid:
        uses: ./.github/workflows/android.yml
        secrets:
          CODESIGNING_DEPLOY_KEY: ${{ secrets.CODESIGNING_DEPLOY_KEY }}
          GOOGLE_PLAY_JSON_KEY: ${{ secrets.GOOGLE_PLAY_JSON_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
    
 #   ios:
 #       uses: ./.github/workflows/ios.yml
