name: Build & Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
    droid:
        uses: ./.github/workflows/android.yml
        with:
          flutter-version: '3.19.3'
        secrets:
          CODESIGNING_DEPLOY_KEY: ${{ secrets.CODESIGNING_DEPLOY_KEY }}
          GOOGLE_PLAY_JSON_KEY: ${{ secrets.GOOGLE_PLAY_JSON_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          LOGIT_API_KEY: ${{ secrets.LOGIT_API_KEY }}
          GOOGLE_SERVICES_JSON_G4K: ${{ secrets.GOOGLE_SERVICES_JSON_G4K }}
    ios:
         uses: ./.github/workflows/ios.yml
         with:
          flutter-version: '3.19.3'
         secrets:
          CODESIGNING_DEPLOY_KEY: ${{ secrets.CODESIGNING_DEPLOY_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APPSTORECONNECT_PRIVATE_KEY: ${{ secrets.APPSTORECONNECT_PRIVATE_KEY }}
          GITHUB_API_TOKEN: ${{ secrets.PERSONAL_ACCESS_KEY }}
          LOGIT_API_KEY: ${{ secrets.LOGIT_API_KEY }}
          GOOGLE_SERVICES_PLIST_G4K: ${{ secrets.GOOGLE_SERVICES_PLIST_G4K }}
